services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: osysdb
    environment:
      MYSQL_ROOT_PASSWORD: hola1234
      MYSQL_DATABASE: osys
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-phola1234"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  api:
    depends_on:
      mysqldb:
        condition: service_healthy
        restart: true
    container_name: apiosys
    build: 
      context: ./api
      dockerfile: dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "4000"

  
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "80:80"
    
      

